pipeline_name: OCR
text_type: general
use_doc_preprocessor: True
use_textline_orientation: True
DocPreprocessor:
  split_pdf_into_pages: True
  batch_size: 1
SubModules:
  TextDetection:
    module_name: text_detection
    model_name: PP-OCRv5_server_det
    model_dir: null
    limit_side_len: 960
    limit_type: max
    max_side_limit: 4000
    thresh: 0.3
    box_thresh: 0.6
    unclip_ratio: 1.5
  TextLineOrientation:
    module_name: textline_orientation
    model_name: PP-LCNet_x1_0_textline_ori
    model_dir: null
    batch_size: 2
  TextRecognition:
    module_name: text_recognition
    model_name: eslav_PP-OCRv5_mobile_rec
    model_dir: null
    batch_size: 2
  TableStructure:
    module_name: table_structure
    model_name: PP-StructureV2
    model_dir: null
    output_format: table
